#!/usr/bin/env sh

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          autofocus
yabai -m config window_placement             second_child
yabai -m config window_topmost               on
yabai -m config window_opacity               off
yabai -m config window_opacity_duration      0.0
yabai -m config window_shadow                on
yabai -m config window_border                off
yabai -m config window_border_width          4
yabai -m config active_window_border_color   0xff775759
yabai -m config normal_window_border_color   0xff505050
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 on
yabai -m config mouse_modifier               ctrl
yabai -m config mouse_action1                move
yabai -m config mouse_action2                resize

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   5

# Rules
yabai -m rule --add title='^System Preferences$' manage=off
yabai -m rule --add title='Copy' manage=off
yabai -m rule --add app='App Store' manage=off
yabai -m rule --add app='Fantastical$' manage=off
yabai -m rule --add app="thinkorswim$" manage=off
yabai -m rule --add app='Parallels Desktop' manage=off
yabai -m rule --add app='Microsoft Teams' manage=off
yabai -m rule --add app='Microsoft Outlook' manage=off
yabai -m rule --add title='• Calendar • api@microsoft.com$' manage=off
yabai -m rule --add app='Emacs' manage=on space=4

echo "yabai configuration loaded.."
